server:
  port: ${SERVER_PORT}

spring:
  config.import: optional:file:./env.properties
  application.name: ${APPLICATION_NAME}
  main.banner-mode: off

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
#      ddl-auto: validate
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      register-mbeans: true

  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
      file-size-threshold: 100MB
      enabled: true
  mvc.async.request-timeout: 600000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.messaging.simp: DEBUG