server:
  port: ${SERVER_PORT}

spring:
  config.import: optional:file:./env.properties
  application.name: ${APPLICATION_NAME}
  main.banner-mode: off

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.messaging.simp: DEBUG